[project]
name = "gruntle-helper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asgiref==3.11.0",
    "beautifulsoup4==4.14.3",
    "django==6.0",
    "django-ckeditor==6.7.3",
    "django-ckeditor-5==0.2.18",
    "django-editorjs==0.2.1",
    "django-js-asset==3.1.2",
    "django-pygmentify==0.3.7",
    "django-taggit==6.1.0",
    "pillow==12.1.0",
    "pygments==2.19.2",
    "soupsieve==2.8.1",
    "sqlparse==0.5.5",
    "typing-extensions==4.15.0",
]
