# Generated by Django 5.0.1 on 2024-02-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kivyapp', '0002_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code_example',
            field=models.TextField(max_length=1000),
        ),
    ]
