# Generated by Django 5.0.1 on 2024-02-05 17:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kivyapp', '0003_alter_article_code_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code_example',
            field=ckeditor.fields.RichTextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=4000),
        ),
    ]
